name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: 'x64'


    - name: Update Git Submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_SHARED_LIBS=FALSE -G "Ninja" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cd ${{github.workspace}}/build
        cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyArtifact
        path: ${{github.workspace}}/build
  Windows-Mingw-Build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update Git submodules
      run: git submodule update --init --recursive

    - name: Configure CMake

      run: cmake -B D:\a\Eat-the-Mushroom\Eat-the-Mushroom/build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=FALSE -DCMAKE_C_COMPILER=C:/ProgramData/chocolatey/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/ProgramData/chocolatey/bin/g++.exe -G "Ninja"

    - name: Build
      run: cmake --build D:\a\Eat-the-Mushroom\Eat-the-Mushroom/build --config Release
    
    - name: Test
      run: |
        echo "Test Coming Soon..."

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows-Mingw
        path: ${{ github.workspace }}/build
