name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: 'x64'


    - name: Update Git Submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_SHARED_LIBS=FALSE -G "Ninja" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cd ${{github.workspace}}/build
        cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyArtifact
        path: ${{github.workspace}}/build
